server:
  port: 9090
  servlet:
    context-path: /bookStudy
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  profiles:
    active: test
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /index.html
      - /img/**
      - /fonts/**
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /sys/admin/verifyCode

