server:
  port: 9090
  servlet:
    context-path: /bookStudy
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  profiles:
    active: test

#以下为公用属性配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

