spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Root123456!
    driver-class-name: com.mysql.jdbc.Driver
#redis相关配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 200
        max-wait: 3000ms
        min-idle: 20

elasticsearch:
  cluster:
    name: docker-cluster
    nodes: 127.0.0.1:9300
  client:
    transport:
      sniff: false
    ignore:
      cluster:
        name: true
    ping:
      timeout: 5s
    nodes:
      sampler:
        interval: 5s
